# Generated by Django 3.0.8 on 2020-07-29 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ecomuser',
            name='status',
            field=models.CharField(choices=[('ISVRF', 'Is Verified'), ('AV', 'Active'), ('INAV', 'In Active')], default='AV', max_length=10),
        ),
    ]
