# Generated by Django 3.0.8 on 2020-08-24 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20200731_0839'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='is_live',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='is_live',
            field=models.BooleanField(default=False),
        ),
    ]
